# Generated by Django 4.1 on 2022-08-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased',
            name='menuItem',
        ),
        migrations.AddField(
            model_name='purchased',
            name='recipeRequirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.reciperequirement'),
        ),
    ]
