# Generated by Django 4.1 on 2022-08-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
