# Generated by Django 4.1 on 2022-08-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_purchased_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='totalRevenue',
            field=models.FloatField(default=0.0),
        ),
    ]
