# Generated by Django 4.1 on 2022-08-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_purchased_totalrevenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased',
            name='totalRevenue',
        ),
    ]
