# Generated by Django 4.1 on 2022-08-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_purchased_totalrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='revenue',
            field=models.FloatField(default=0),
        ),
    ]
