# Generated by Django 4.1 on 2022-08-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_purchased_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased',
            name='revenue',
        ),
    ]
